add jar hdfs:///user/hive/lib/json-serde-1.3.8-jar-with-dependencies.jar;
add jar hdfs:///user/hive/lib/json-udf-1.3.8-jar-with-dependencies.jar;

DROP TABLE if exists test_rs;

CREATE EXTERNAL TABLE test_rs ( subreddit string, title string, selftext string, created_utc float, `year` int, `month` int, `day` int )
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION '/user/bda_reddit_pw/historical_reddit_processed/jsonData/';
